Initial proposal for a Gin wrapper that provide graceful shutdown.
gin-contrib/graceful pull request #2
Opened 2023-06-20 19:02 UTC by cedric-appdirect

The content of .github come from `gin-contrib/logger` and the test are inspired by gin test.

2023-07-28 12:41 UTC, appleboy requested changes

2023-07-28 12:41 UTC, appleboy commented on coverage.txt
> +mode: atomic
Add this file to ignore list.

2023-07-28 12:41 UTC, appleboy commented on .gitignore
> +coverage.out
coverage.*

2023-07-28 12:41 UTC, appleboy commented on .github/workflows/go.yml
> +          version: v1.49.0
latest

2023-07-28 12:41 UTC, appleboy commented on .github/workflows/go.yml
> +        go: [1.17, 1.18, 1.19, '1.20']
remove 1.17

2023-07-28 15:39 UTC, cedric-appdirect commented on coverage.txt
> +mode: atomic
Oops, good catch.

2023-08-18 17:49 UTC, cedric-appdirect commented
I think I have addressed all the first batch of comments. Is there anything I can do to help?

2023-08-18 22:42 UTC, appleboy approved these changes

2023-08-18 22:42 UTC, appleboy commented
@cedric-appdirect Thanks.

2023-08-18 22:43 UTC, merged